[tool.black]
line-length = 88
target-version = ["py310"]

[tool.coverage.run]
omit = ["config.py", "config-3.py"]

[tool.docformatter]
black = true

[tool.ruff]
line-length = 88
target-version = "py310"
