name: CI/CD - Todos

on:
  pull_request:
    paths:
      - "src/todos/**"
  push:
    branches: 
      - main
      - "releases/**"
    paths:
      - "src/todos/**"
env:
  PROJECT_NAME: todos
jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      PROJECT_NAME: ${{ env.PROJECT_NAME }}
  publish:
    if: ${{ github.event_name == 'push' }}
    needs: [build]
    uses: ./.github/workflows/publish.yaml
    with:
      PROJECT_NAME: ${{ env.PROJECT_NAME }}
      APP_NAME: todos
      ENVIRONMENT: ${{ github.ref == 'refs/heads/main' && 'stage' || 'prod' }}
