name: CI/CD - Todos

on:
  pull_request:
    paths:
      - "src/todos/**"
  push:
    branches: 
      - main
      - "releases/**"
    paths:
      - "src/todos/**"
jobs:
  default:
    uses: ./.github/workflows/default.yaml
    with:
      PROJECT_NAME: todos
  deploy:
    if: ${{ github.event_name == 'push' }}
    needs: [default]
    uses: ./.github/workflows/deploy.yaml
    with:
      PROJECT_NAME: todos
      APP_NAME: todos
      ENVIRONMENT: ${{ github.ref == 'refs/heads/main' && 'stage' || 'prod' }}
